# NoteBook Ingest dataset life_expectancy_dataset

***Author:*** Frederick Salazar <br>
***Data Source:*** World Bank <br>
***Description:*** this dataset contain the historical record of the life expectancy at birth from 1960 to present of all countries

## Importations and configurations

In [20]:
#library importations

import pandas as pd

import os
import requests
import zipfile
from io import BytesIO

version = 1.0

In [21]:
raw = './data/raw'
processed_data = './data/processed'
output_data = './data/output'

output_dataset = './data/processed/life_expectancy_dataset.csv'

In [22]:
def download_data(data_source_in):
    """this function get files from url and save it in the raw folder

    Args:
        data_source_in (String): url of the file to download
    """
    response = requests.get(data_source_in)

    if response.status_code == 200:
        # Leer el contenido del archivo ZIP en memoria
        zip_file = BytesIO(response.content)
        
        # Descomprimir el contenido del ZIP directamente en el directorio
        with zipfile.ZipFile(zip_file) as z:
            z.extractall(raw)

## Download and read data

In [23]:
#download dataset of women life expectancy
download_data('https://api.worldbank.org/v2/es/indicator/SP.DYN.LE00.FE.IN?downloadformat=csv')

In [24]:
#download dataset of men life expectancy
download_data('https://api.worldbank.org/v2/es/indicator/SP.DYN.LE00.MA.IN?downloadformat=csv')

## load data

In [25]:
for file in os.listdir(raw):
    print(file)
    if file.startswith('API_SP.DYN.LE00.FE.IN_DS2'):
        df_data_women = pd.read_csv(f'{raw}/{file}', skiprows=4)
        df_data_women = df_data_women.iloc[:, :-1]
    if file.startswith('API_SP.DYN.LE00.MA.IN_DS2'):
        df_data_men = pd.read_csv(f'{raw}/{file}', skiprows=4)
        df_data_men = df_data_men.iloc[:, :-1]
    #load metadata of country codes
    if file.startswith('country_codes_list'):
        df_country_code = pd.read_csv(f'{raw}/{file}',
                                    sep=',',
                                    skiprows=0)

API_SP.DYN.LE00.FE.IN_DS2_es_csv_v2_6527.csv
.gitkeep
API_SP.DYN.LE00.MA.IN_DS2_es_csv_v2_2773.csv
Metadata_Country_API_SP.DYN.LE00.FE.IN_DS2_es_csv_v2_6527.csv
Metadata_Indicator_API_SP.DYN.LE00.MA.IN_DS2_es_csv_v2_2773.csv
Metadata_Country_API_SP.DYN.LE00.MA.IN_DS2_es_csv_v2_2773.csv
country_codes_list.csv
Metadata_Indicator_API_SP.DYN.LE00.FE.IN_DS2_es_csv_v2_6527.csv

In [26]:
df_data_women.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,"Esperanza de vida al nacer, mujeres (años)",SP.DYN.LE00.FE.IN,67.783000,68.269000,68.579000,68.992000,69.180000,69.449000,...,78.614000,78.644000,78.486000,78.794000,78.854000,79.010000,78.445000,77.315000,77.681000,NaN
1,NaN,AFE,"Esperanza de vida al nacer, mujeres (años)",SP.DYN.LE00.FE.IN,45.718381,46.129297,46.490941,46.782763,47.365993,47.431575,...,63.641430,64.190803,64.867787,65.305072,65.829089,66.218859,65.832008,65.073170,65.480353,NaN
2,Afganistán,AFG,"Esperanza de vida al nacer, mujeres (años)",SP.DYN.LE00.FE.IN,33.285000,33.813000,34.297000,34.773000,35.246000,35.702000,...,64.274000,64.576000,65.096000,66.099000,66.458000,66.677000,65.432000,65.279000,66.213000,NaN
3,NaN,AFW,"Esperanza de vida al nacer, mujeres (años)",SP.DYN.LE00.FE.IN,39.381940,39.700643,39.930179,40.277182,40.602218,40.835536,...,56.803684,57.084297,57.362785,57.758715,58.030838,58.467209,58.277423,58.035597,58.657987,NaN
4,Angola,AGO,"Esperanza de vida al nacer, mujeres (años)",SP.DYN.LE00.FE.IN,39.918000,40.097000,40.399000,40.665000,40.990000,41.384000,...,62.472000,63.094000,63.434000,64.019000,64.717000,64.922000,64.982000,64.307000,64.541000,NaN

In [27]:
df_data_men.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,"Esperanza de vida al nacer, varones (años)",SP.DYN.LE00.MA.IN,60.582000,60.880000,61.023000,61.372000,61.522000,61.686000,...,72.448000,72.569000,72.582000,72.838000,73.096000,73.286000,72.828000,71.798000,72.145000,NaN
1,NaN,AFE,"Esperanza de vida al nacer, varones (años)",SP.DYN.LE00.MA.IN,42.560295,42.761640,43.133980,43.172863,43.729603,43.700803,...,59.030487,59.519440,60.023772,60.540422,60.907677,61.290639,60.814670,59.889797,60.352379,NaN
2,Afganistán,AFG,"Esperanza de vida al nacer, varones (años)",SP.DYN.LE00.MA.IN,31.870000,32.409000,32.883000,33.346000,33.828000,34.289000,...,60.812000,60.760000,61.193000,60.105000,59.923000,60.619000,59.866000,58.915000,59.766000,NaN
3,NaN,AFW,"Esperanza de vida al nacer, varones (años)",SP.DYN.LE00.MA.IN,36.451144,36.765563,37.572433,37.883420,38.104773,38.429585,...,54.926835,55.190569,55.673515,55.900292,56.233120,56.542177,56.105952,55.880937,56.539457,NaN
4,Angola,AGO,"Esperanza de vida al nacer, varones (años)",SP.DYN.LE00.MA.IN,36.585000,34.704000,34.950000,35.247000,35.539000,35.884000,...,57.606000,58.213000,58.741000,59.331000,59.582000,59.977000,59.584000,59.029000,59.351000,NaN

## Transform data

In [28]:
#upper all strings

df_data_women = df_data_women.applymap(lambda x: x.upper() if isinstance(x, str) else x)
df_data_men = df_data_men.applymap(lambda x: x.upper() if isinstance(x, str) else x)
df_country_code = df_country_code.applymap(lambda x: x.upper() if isinstance(x, str) else x)

/var/folders/34/mqqssx0s7jd53nv2vzj0plc00000gn/T/ipykernel_18803/2794204635.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_data_women = df_data_women.applymap(lambda x: x.upper() if isinstance(x, str) else x)
/var/folders/34/mqqssx0s7jd53nv2vzj0plc00000gn/T/ipykernel_18803/2794204635.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_data_men = df_data_men.applymap(lambda x: x.upper() if isinstance(x, str) else x)
/var/folders/34/mqqssx0s7jd53nv2vzj0plc00000gn/T/ipykernel_18803/2794204635.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_country_code = df_country_code.applymap(lambda x: x.upper() if isinstance(x, str) else x)

## Transform data structure from wide to long table

In [29]:
df_data_women = pd.melt(df_data_women,
                        id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                        var_name='Year',
                        value_vars=df_data_women.iloc[:, :-1].columns,
                        value_name='life_expectancy_women')

In [30]:
df_data_men = pd.melt(df_data_men,
                      id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                      var_name='Year',
                      value_vars=df_data_men.iloc[:, :-1].columns,
                      value_name='life_expectancy_men')

In [31]:
df_data_women = df_data_women[['Country Name', 
                               'Country Code', 
                               'Year', 
                               'life_expectancy_women']]

In [32]:
df_data_men = df_data_men[['Country Code', 
                           'Year', 
                           'life_expectancy_men']]

## Union of life expectancy of women and men

In [33]:
df_life_expectancy = pd.merge(df_data_women,
                              df_data_men,
                              on=['Country Code', 'Year'],
                              how='inner')

In [34]:
df_life_expectancy.columns = ['country_name', 'country_code', 'year', 'life_expectancy_women', 'life_expectancy_men']

df_life_expectancy = df_life_expectancy[['country_code', 'country_name', 'year', 'life_expectancy_women','life_expectancy_men']]

In [35]:
df_life_expectancy = pd.merge(df_life_expectancy,
                              df_country_code,
                              left_on='country_code',
                              right_on='alpha-3',
                              how='inner')

In [36]:
df_life_expectancy = df_life_expectancy[['country_code',
                                         'country_name',
                                         'region',
                                         'sub-region',
                                         'intermediate-region',
                                         'year',
                                         'life_expectancy_women',
                                         'life_expectancy_men']]

## Set NaN values

In [37]:
df_life_expectancy['life_expectancy_women'].fillna(0, inplace=True)
df_life_expectancy['life_expectancy_men'].fillna(0, inplace=True)

/var/folders/34/mqqssx0s7jd53nv2vzj0plc00000gn/T/ipykernel_18803/627997171.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_life_expectancy['life_expectancy_women'].fillna(0, inplace=True)
/var/folders/34/mqqssx0s7jd53nv2vzj0plc00000gn/T/ipykernel_18803/627997171.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_life_expectancy['life_expectancy_men'].fillna(0, inplace=True)

In [38]:
df_life_expectancy = df_life_expectancy.sort_values(by=['country_name', 'year'], ascending=True)

## Save processed data

In [39]:
df_life_expectancy.to_csv(output_dataset, index=False, float_format="%.2f", sep=';', decimal=',')